spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: kaizen
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # Cria as tabelas automaticamente com base nas suas classes Java
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Configurações de E-mail
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 11b336a3e08d65
    password: e14231d4d8b748
    properties:
      mail:
        confirm:
          debug: true # Ajuda a ver erros de envio no console
        smtp:
          auth: true
          starttls:
            enable: true
google:
  books:
    api-key: ${GOOGLE_BOOKS_API_KEY:sla}
logging:
  level:
    org.springframework.web.reactive.function.client.WebClient: DEBUG